### ISSUE TITLE
Podspec version 10.

### ISSUE THREAD

**Issue by lassecapel** [mduthey/react-native-snapchat-login#1]
Hi,

In the IOS podspec the minimal ios version is defined as version 10.

```yaml
s.platform  = :ios, "10.0"
```
Most react native project have >= 9.

Is there a specific reason to put the version on 10 because in that case many people have to upgrade their project to use the library.

**Comment by mduthey** [comment]
Hello @lassecapel

Yes, the reason for that is because of the library LoginKit from Snap kit 
(https://docs.snapchat.com/docs/login-kit) has as requirement iOS 10+

```
Requirements
Client ID from the developer portal
iOS version 10.0+
```

**Comment by lassecapel** [comment]
thanks
