### ISSUE TITLE
Android package name conflict with another library

### ISSUE THREAD

**Issue by velhari** [mduthey/react-native-snapchat-login#11]
Hi,

I am trying to integrate snapchat social login in a mobile app. After installing your library i am getting following build error. 

"

java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: |  
-- | --
com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: |  
com.android.tools.r8.CompilationFailedException: Compilation failed to complete |  
com.android.tools.r8.utils.AbortException: Error: Program type already present: com.reactlibrary.BuildConfig |  

"

After analyzing the issue, i found that the package name used for Android is "com.reactlibrary" which is conflicting with another package. So, please can you change the android package name to unique one like this 'com.mduthey.snapchat' or any your wish.

Thanks and expecting favorable reply

**Comment by mduthey** [comment]
Ready on version 1.1.0
Thanks for the PR! #12

**Comment by velhari** [comment]
> Ready on version 1.1.0
> Thanks for the PR! #12

Thanks @mduthey
