### ISSUE TITLE
[iOS] some APIs were removed from SnapSDK v1.4

### ISSUE THREAD

**Issue by peteroid** [mduthey/react-native-snapchat-login#13]
### Context
There are a few APIs using in this library were removed in the latest version of SnapSDK. 

This is one of the examples.
https://github.com/mduthey/react-native-snapchat-login/blob/5fadaf6cea5f4798d057117c06cda8910c652175/ios/SnapchatLogin.m#L37

SnapSDK ref: https://docs.snapchat.com/docs/changelog/#modifications

### Workaround
Patch the podspec after refreshing the `node_modules` library 
https://gist.github.com/peteroid/3bd3d524206bb6d367c4a0c8fd20e5a4

**Comment by mduthey** [comment]
Thanks @peteroid I release it on the 1.1.1
